### DISCUSSION TITLE
Ollama mode dont work on windows

### DISCUSSION THREAD

**Discussion by Milor123** [nextai-translator/nextai-translator#1738] [Q&A]
Hey guys, today I've download it in windows and not work for me (in linux works well)

I have ollama client installed with scoop and ollama server in a docker (it works if I run ollama from my cmd or  other dockers apps using it.)
![image](https://github.com/user-attachments/assets/3ef6d791-5894-4e88-ba19-13a33fa2dfb5)

but this app stuck loading in windows, never end of loading. If I press "Go Back" then settings are not applied :/

What should i do guys?

my ollama compose file:
```yml
name: Ollama
services:


    ollama:
        privileged: true
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: 
                          - gpu
        volumes:
            - ollama_data:/root/.ollama
        ports:
            - 11434:11434
        environment:
            - OLLAMA_HOST=0.0.0.0
            - OLLAMA_FLASH_ATTENTION=1
            - OLLAMA_LLAMA_EXTRA_ARGS="-fa"
            - OLLAMA_ORIGINS="*"

        container_name: ollama
        image: ollama/ollama
        restart: always
        #extra_hosts:
            #- host.docker.internal:host-gateway

volumes:
    #external: true
    ollama_data:

```
